package org.fastnate.generator.context;

import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;

import jakarta.persistence.GenerationType;

import org.fastnate.generator.statements.ColumnExpression;
import org.fastnate.generator.statements.PrimitiveColumnExpression;
import org.fastnate.generator.statements.StatementsWriter;
import org.fastnate.generator.statements.TableStatement;

import lombok.Getter;
import lombok.Setter;

/**
 * Generates the next value for a primary key of type {@link GenerationType#UUID}.
 *
 * @author Tobias Liefke
 */
public class UuidGenerator extends IdGenerator<String> {

	/** The settings key for {@link #randomUuid}. */
	public static final String RANDOUM_UUIDS_KEY = "fastnate.generator.uuid.random";

	/** The count of bytes that we use for generating a UUID. */
	private static final int NEXT_VALUE_BYTE_COUNT = 8;

	/** The count of characters of a UUID generated by this generator. */
	public static final int UUID_LENGTH = 36;

	/** The table for which we are used. */
	@Getter
	private final GeneratorTable table;

	/**
	 * Indicates that we generate a different UUID on each run.
	 *
	 * Otherwise we generate a UUID which is calculated from the table name and the current iteration.
	 */
	@Getter
	@Setter
	private boolean randomUuid;

	/** The current value, only relevant if {@link #randomUuid} is {@code false}. */
	private final byte[] uuidBytes;

	/**
	 * Creates a new instance of {@link UuidGenerator}.
	 *
	 * @param table
	 *            the table for which we are used
	 */
	public UuidGenerator(final GeneratorTable table) {
		this.table = table;
		this.randomUuid = "true".equals(table.getContext().getSettings().getOrDefault(RANDOUM_UUIDS_KEY, "false"));
		final byte[] tableNameBytes = table.getName().getBytes();
		this.uuidBytes = Arrays.copyOf(tableNameBytes, tableNameBytes.length + NEXT_VALUE_BYTE_COUNT);
	}

	@Override
	public void addNextValue(final TableStatement statement, final GeneratorColumn column, final String nextValue) {
		statement.setColumnValue(column,
				PrimitiveColumnExpression.create(nextValue, column.getTable().getContext().getDialect()));
	}

	@Override
	public void alignNextValue(final StatementsWriter writer) throws IOException {
		// Ignore
	}

	@Override
	public String createNextValue(final Class<String> propertyClass) {
		if (this.randomUuid) {
			return UUID.randomUUID().toString();
		}
		for (int i = this.uuidBytes.length - 1; i >= 0; i--) {
			if (this.uuidBytes[i] != -1) {
				this.uuidBytes[i]++;
				break;
			}
			this.uuidBytes[i] = 0;
		}
		return UUID.nameUUIDFromBytes(this.uuidBytes).toString();
	}

	@Override
	public ColumnExpression getExpression(final GeneratorTable targetTable, final GeneratorColumn column,
			final String id, final boolean whereExpression) {
		return PrimitiveColumnExpression.create(id, targetTable.getContext().getDialect());
	}

	@Override
	public boolean isPostIncrement() {
		return false;
	}

}
