package org.fastnate.generator.statements;

import org.fastnate.generator.EntitySqlGenerator;

/**
 * Base class for statements generated by an {@link EntitySqlGenerator}.
 *
 * @author Tobias Liefke
 */
public abstract class EntityStatement {

	/**
	 * Prints this statement as SQL.
	 *
	 * @return the SQL statement
	 */
	public abstract String toSql();

	@Override
	public String toString() {
		return toSql();
	}

}
