-- Role: fastnate

CREATE ROLE fastnate LOGIN UNENCRYPTED PASSWORD 'fastnate' VALID UNTIL 'infinity';

-- Database: fastnate

CREATE DATABASE fastnate WITH OWNER = postgres ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION LIMIT = -1;

ALTER DEFAULT PRIVILEGES GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO fastnate;
